/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2021-02-16T20:45:07.953-05:00
  3.32.0.3
  
  Standalone prediction code with sample test data for DRFModel named DRF_model_python_1613526296143_1

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/DRF_model_python_1613526296143_1 > DRF_model_python_1613526296143_1.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m DRF_model_python_1613526296143_1.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;

public class DRF_model_python_1613526296143_1 {

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 5; }
  public int nclasses() { return 2; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_DRF_model_python_1613526296143_1.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 2;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* displacement */ null,
    /* power */ null,
    /* weight */ null,
    /* acceleration */ null,
    /* year */ null,
    /* economy_20mpg */ DRF_model_python_1613526296143_1_ColInfo_5.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.3723076923076923,0.6276923076923077};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {0.3723076923076923,0.6276923076923077};

  public String getUUID() { return Long.toString(4597120739987111725L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    DRF_model_python_1613526296143_1_Forest_0.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_1.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_2.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_3.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_4.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_5.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_6.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_7.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_8.score0(data,preds);
    DRF_model_python_1613526296143_1_Forest_9.score0(data,preds);
    double sum = 0;
    for(int i=1; i<preds.length; i++) { sum += preds[i]; }
    if (sum>0) for(int i=1; i<preds.length; i++) { preds[i] /= sum; }
    preds[0] = GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.6871434272305222);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_DRF_model_python_1613526296143_1 implements java.io.Serializable {
  public static final String[] VALUES = new String[5];
  static {
    NamesHolder_DRF_model_python_1613526296143_1_0.fill(VALUES);
  }
  static final class NamesHolder_DRF_model_python_1613526296143_1_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "displacement";
      sa[1] = "power";
      sa[2] = "weight";
      sa[3] = "acceleration";
      sa[4] = "year";
    }
  }
}
// The class representing column economy_20mpg
class DRF_model_python_1613526296143_1_ColInfo_5 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    DRF_model_python_1613526296143_1_ColInfo_5_0.fill(VALUES);
  }
  static final class DRF_model_python_1613526296143_1_ColInfo_5_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "0";
      sa[1] = "1";
    }
  }
}

class DRF_model_python_1613526296143_1_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_0_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_0_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* power */] <97.5f ? 
         (Double.isNaN(data[1]) || data[1 /* power */] <84.5f ? 
             (Double.isNaN(data[2]) || data[2 /* weight */] <2529.5f ? 
                0.0f : 
                0.2f) : 
             (Double.isNaN(data[4]) || data[4 /* year */] <76.5f ? 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2674.0f ? 
                    0.14285715f : 
                    0.7f) : 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2798.5f ? 
                    0.0f : 
                    0.1f))) : 
         (data[0 /* displacement */] <228.28613f ? 
             (data[2 /* weight */] <2798.5f ? 
                0.0f : 
                0.53846157f) : 
             (Double.isNaN(data[4]) || data[4 /* year */] <77.5f ? 
                1.0f : 
                0.8f)));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_0_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* power */] <97.5f ? 
         (Double.isNaN(data[1]) || data[1 /* power */] <84.5f ? 
             (Double.isNaN(data[2]) || data[2 /* weight */] <2529.5f ? 
                1.0f : 
                0.8f) : 
             (Double.isNaN(data[4]) || data[4 /* year */] <76.5f ? 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2674.0f ? 
                    0.85714287f : 
                    0.3f) : 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2798.5f ? 
                    1.0f : 
                    0.9f))) : 
         (data[0 /* displacement */] <228.28613f ? 
             (data[2 /* weight */] <2798.5f ? 
                1.0f : 
                0.46153846f) : 
             (Double.isNaN(data[4]) || data[4 /* year */] <77.5f ? 
                0.0f : 
                0.2f)));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_1_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_1_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0]) || data[0 /* displacement */] <212.49512f ? 
         (Double.isNaN(data[0]) || data[0 /* displacement */] <159.61607f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <86.5f ? 
                0.0f : 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2784.5f ? 
                     (data[2 /* weight */] <2412.5f ? 
                        0.2f : 
                        0.0f) : 
                    0.3f)) : 
            0.3f) : 
         (data[2 /* weight */] <3739.0f ? 
             (Double.isNaN(data[4]) || data[4 /* year */] <75.5f ? 
                0.94736844f : 
                0.5294118f) : 
            1.0f));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_1_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0]) || data[0 /* displacement */] <212.49512f ? 
         (Double.isNaN(data[0]) || data[0 /* displacement */] <159.61607f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <86.5f ? 
                1.0f : 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2784.5f ? 
                     (data[2 /* weight */] <2412.5f ? 
                        0.8f : 
                        1.0f) : 
                    0.7f)) : 
            0.7f) : 
         (data[2 /* weight */] <3739.0f ? 
             (Double.isNaN(data[4]) || data[4 /* year */] <75.5f ? 
                0.05263158f : 
                0.47058824f) : 
            0.0f));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_2_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_2_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* weight */] <3096.5f ? 
         (Double.isNaN(data[0]) || data[0 /* displacement */] <198.58398f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <106.5f ? 
                 (data[4 /* year */] <73.5f ? 
                     (data[4 /* year */] <71.5f ? 
                        0.0f : 
                        0.15384616f) : 
                    0.0f) : 
                0.2f) : 
            0.8f) : 
         (Double.isNaN(data[4]) || data[4 /* year */] <77.5f ? 
             (data[1 /* power */] <106.5f ? 
                0.8333333f : 
                1.0f) : 
             (Double.isNaN(data[3]) || data[3 /* acceleration */] <16.209375f ? 
                0.75f : 
                0.4f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_2_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* weight */] <3072.5f ? 
         (Double.isNaN(data[0]) || data[0 /* displacement */] <155.72266f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <82.5f ? 
                1.0f : 
                 (data[2 /* weight */] <2342.5f ? 
                    0.8333333f : 
                     (Double.isNaN(data[2]) || data[2 /* weight */] <2735.5f ? 
                        1.0f : 
                        0.9f))) : 
            0.42857143f) : 
         (data[4 /* year */] <75.5f ? 
            0.0f : 
             (data[1 /* power */] <106.5f ? 
                 (data[3 /* acceleration */] <17.95078f ? 
                    0.5f : 
                    0.6f) : 
                 (data[2 /* weight */] <3848.5f ? 
                    0.2f : 
                    0.0f))));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_3_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_3_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* weight */] <3096.5f ? 
         (Double.isNaN(data[0]) || data[0 /* displacement */] <198.58398f ? 
             (data[4 /* year */] <73.5f ? 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2273.5f ? 
                    0.07692308f : 
                    0.4f) : 
                0.0f) : 
            0.41666666f) : 
         (data[0 /* displacement */] <231.66992f ? 
            0.42105263f : 
             (Double.isNaN(data[4]) || data[4 /* year */] <76.5f ? 
                1.0f : 
                0.8666667f)));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_3_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* weight */] <3072.5f ? 
         (Double.isNaN(data[0]) || data[0 /* displacement */] <198.58398f ? 
             (data[4 /* year */] <73.5f ? 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2274.5f ? 
                    0.9230769f : 
                    0.6f) : 
                1.0f) : 
            0.6363636f) : 
         (data[0 /* displacement */] <231.66992f ? 
            0.57894737f : 
             (Double.isNaN(data[4]) || data[4 /* year */] <76.5f ? 
                0.0f : 
                0.13333334f)));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_4_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_4_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* weight */] <3096.5f ? 
         (Double.isNaN(data[2]) || data[2 /* weight */] <2749.5f ? 
             (data[4 /* year */] <73.5f ? 
                 (data[4 /* year */] <71.5f ? 
                    0.0f : 
                    0.16666667f) : 
                0.0f) : 
             (Double.isNaN(data[0]) || data[0 /* displacement */] <189.56055f ? 
                0.0625f : 
                0.5f)) : 
         (data[0 /* displacement */] <231.66992f ? 
            0.5263158f : 
             (Double.isNaN(data[4]) || data[4 /* year */] <75.5f ? 
                1.0f : 
                0.8333333f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_4_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* weight */] <3072.5f ? 
         (Double.isNaN(data[2]) || data[2 /* weight */] <2749.5f ? 
             (data[4 /* year */] <73.5f ? 
                 (data[4 /* year */] <71.5f ? 
                    1.0f : 
                    0.8333333f) : 
                1.0f) : 
             (Double.isNaN(data[0]) || data[0 /* displacement */] <189.56055f ? 
                0.9375f : 
                0.5f)) : 
         (data[0 /* displacement */] <231.66992f ? 
            0.47368422f : 
             (Double.isNaN(data[4]) || data[4 /* year */] <75.5f ? 
                0.0f : 
                0.16666667f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_5_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_5_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[3 /* acceleration */] <13.750391f ? 
         (data[0 /* displacement */] <201.96777f ? 
            0.14285715f : 
             (Double.isNaN(data[4]) || data[4 /* year */] <76.5f ? 
                1.0f : 
                0.9166667f)) : 
         (Double.isNaN(data[2]) || data[2 /* weight */] <3018.5f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <94.5f ? 
                0.0f : 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2761.0f ? 
                    0.0f : 
                    0.3f)) : 
             (data[2 /* weight */] <3436.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* acceleration */] <16.685444f ? 
                    0.78571427f : 
                    0.5f) : 
                1.0f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_5_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[3 /* acceleration */] <13.750391f ? 
         (data[0 /* displacement */] <201.96777f ? 
            0.85714287f : 
             (Double.isNaN(data[4]) || data[4 /* year */] <76.5f ? 
                0.0f : 
                0.083333336f)) : 
         (Double.isNaN(data[2]) || data[2 /* weight */] <3018.5f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <94.5f ? 
                1.0f : 
                 (Double.isNaN(data[2]) || data[2 /* weight */] <2761.0f ? 
                    1.0f : 
                    0.7f)) : 
             (data[2 /* weight */] <3436.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* acceleration */] <16.685444f ? 
                    0.21428572f : 
                    0.5f) : 
                0.0f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_6_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_6_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0]) || data[0 /* displacement */] <212.49512f ? 
         (Double.isNaN(data[1]) || data[1 /* power */] <84.5f ? 
            0.0f : 
             (Double.isNaN(data[2]) || data[2 /* weight */] <2922.5f ? 
                 (data[2 /* weight */] <2288.5f ? 
                    0.2f : 
                    0.0f) : 
                0.45454547f)) : 
         (data[2 /* weight */] <3429.0f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <102.5f ? 
                0.7692308f : 
                0.41666666f) : 
             (data[2 /* weight */] <3739.5f ? 
                0.8666667f : 
                1.0f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_6_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0]) || data[0 /* displacement */] <212.49512f ? 
         (Double.isNaN(data[1]) || data[1 /* power */] <84.5f ? 
            1.0f : 
             (Double.isNaN(data[2]) || data[2 /* weight */] <2922.5f ? 
                 (data[2 /* weight */] <2288.5f ? 
                    0.8f : 
                    1.0f) : 
                0.54545456f)) : 
         (data[2 /* weight */] <3429.0f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <102.5f ? 
                0.23076923f : 
                0.5833333f) : 
             (data[2 /* weight */] <3739.5f ? 
                0.13333334f : 
                0.0f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_7_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_7_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* power */] <97.5f ? 
         (Double.isNaN(data[2]) || data[2 /* weight */] <3094.5f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <84.0f ? 
                0.0f : 
                 (data[0 /* displacement */] <112.109375f ? 
                    0.3f : 
                     (Double.isNaN(data[0]) || data[0 /* displacement */] <144.89795f ? 
                        0.0f : 
                        0.07692308f))) : 
            0.64285713f) : 
         (data[2 /* weight */] <2922.5f ? 
            0.23076923f : 
             (data[0 /* displacement */] <240.69336f ? 
                0.6f : 
                1.0f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_7_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* power */] <97.5f ? 
         (Double.isNaN(data[2]) || data[2 /* weight */] <3094.5f ? 
             (Double.isNaN(data[1]) || data[1 /* power */] <84.0f ? 
                1.0f : 
                 (data[0 /* displacement */] <112.109375f ? 
                    0.7f : 
                     (Double.isNaN(data[0]) || data[0 /* displacement */] <144.89795f ? 
                        1.0f : 
                        0.9230769f))) : 
            0.35714287f) : 
         (data[2 /* weight */] <2922.5f ? 
            0.7692308f : 
             (data[0 /* displacement */] <240.69336f ? 
                0.4f : 
                0.0f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_8_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_8_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* power */] <97.5f ? 
         (data[4 /* year */] <76.5f ? 
             (Double.isNaN(data[2]) || data[2 /* weight */] <2736.0f ? 
                 (Double.isNaN(data[1]) || data[1 /* power */] <87.5f ? 
                    0.0f : 
                    0.1764706f) : 
                0.7f) : 
             (Double.isNaN(data[0]) || data[0 /* displacement */] <148.20312f ? 
                0.0f : 
                0.27272728f)) : 
         (data[2 /* weight */] <3432.5f ? 
             (data[4 /* year */] <77.5f ? 
                0.5f : 
                0.0f) : 
             (Double.isNaN(data[4]) || data[4 /* year */] <76.5f ? 
                1.0f : 
                0.93333334f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_8_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* power */] <97.5f ? 
         (data[4 /* year */] <76.5f ? 
             (Double.isNaN(data[2]) || data[2 /* weight */] <2736.0f ? 
                 (Double.isNaN(data[1]) || data[1 /* power */] <87.5f ? 
                    1.0f : 
                    0.8235294f) : 
                0.3f) : 
             (Double.isNaN(data[0]) || data[0 /* displacement */] <148.20312f ? 
                1.0f : 
                0.72727275f)) : 
         (data[2 /* weight */] <3432.5f ? 
             (data[4 /* year */] <77.5f ? 
                0.5f : 
                1.0f) : 
             (Double.isNaN(data[4]) || data[4 /* year */] <76.5f ? 
                0.0f : 
                0.06666667f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class DRF_model_python_1613526296143_1_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += DRF_model_python_1613526296143_1_Tree_9_class_0.score0(fdata);
    preds[2] += DRF_model_python_1613526296143_1_Tree_9_class_1.score0(fdata);
  }
}
class DRF_model_python_1613526296143_1_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* power */] <97.5f ? 
         (Double.isNaN(data[0]) || data[0 /* displacement */] <212.49512f ? 
             (Double.isNaN(data[2]) || data[2 /* weight */] <2977.5f ? 
                 (data[3 /* acceleration */] <14.126562f ? 
                    0.09090909f : 
                     (Double.isNaN(data[2]) || data[2 /* weight */] <2687.5f ? 
                        0.013157895f : 
                        0.09090909f)) : 
                0.3f) : 
            0.7692308f) : 
         (Double.isNaN(data[4]) || data[4 /* year */] <77.5f ? 
             (data[1 /* power */] <111.5f ? 
                 (data[0 /* displacement */] <227.91016f ? 
                    0.5f : 
                    0.90909094f) : 
                1.0f) : 
             (Double.isNaN(data[2]) || data[2 /* weight */] <3363.5f ? 
                0.0f : 
                0.75f)));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class DRF_model_python_1613526296143_1_Tree_9_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* power */] <97.5f ? 
         (Double.isNaN(data[0]) || data[0 /* displacement */] <212.49512f ? 
             (Double.isNaN(data[2]) || data[2 /* weight */] <2977.5f ? 
                 (data[3 /* acceleration */] <14.126562f ? 
                    0.90909094f : 
                     (Double.isNaN(data[2]) || data[2 /* weight */] <2687.5f ? 
                        0.9868421f : 
                        0.90909094f)) : 
                0.7f) : 
            0.23076923f) : 
         (Double.isNaN(data[4]) || data[4 /* year */] <77.5f ? 
             (data[1 /* power */] <111.5f ? 
                 (data[0 /* displacement */] <227.91016f ? 
                    0.5f : 
                    0.09090909f) : 
                0.0f) : 
             (Double.isNaN(data[2]) || data[2 /* weight */] <3363.5f ? 
                1.0f : 
                0.25f)));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}


